{
 "title": "Saltwater Sensors",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Saltwater Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    { "expr": "saltwater_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "saltwater_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heater State",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "saltwater_heater_on", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fan State",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "saltwater_fan_on", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Predicted Temp (5m) - (10m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "predict_linear(saltwater_temperature[10m], 3600)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan Power On Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "saltwater_fan_power_on_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saltwater Temperature Delta(10m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "delta(saltwater_temperature[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heater Power On Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "saltwater_heater_power_on_count_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}